import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // tutorialSidebar: [{type: 'autogenerated', dirName: '.'}],

  // But you can create a sidebar manually
  tutorialSidebar: [
    'intro',
    'learning-outcomes',
    {
      type: 'category',
      label: 'Course Modules',
      items: [
        'modules/module-1-ros',
        'modules/module-2-digital-twin',
        'modules/module-3-nvidia-isaac',
        'modules/module-4-vla',
      ],
    },
    'weekly-breakdown',
    'assessments',
    {
      type: 'category',
      label: 'Hardware Requirements',
      items: [
        'hardware/overview',
        'hardware/workstation',
        'hardware/edge-kit',
        'hardware/robot-lab',
        'hardware/cloud-native-lab',
      ],
    },
  ],
};

export default sidebars;
